project_name: articli
builds:
  - env:
      - CGO_ENABLED=0
    binary: acli
    goarch:
      - amd64
      - arm64
    goos:
      - windows
      - linux
      - darwin
#    hooks:
#      post:
#        - upx "{{ .Path }}"
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -w
      - -s
    main: ./cmd/articli
dist: release # The dist folder
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
